version: "3"
services:
  client:
    image: node:16-alpine
    stdin_open: true
    WORKDIR: /usr/src/app
    COPY: client/ /usr/src/app
    ports:
      - "3000:3000"
    networks:
      - mern-app
    command: "yarn start"
  api-server:
    image:
    ports:
      - "8080:8080"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
